name: Test hello world

on:
  pull_request:
    branches:
      - "**"
    paths:
      - "common/hello-world/*"
  push:
    branches:
      - "**"
    paths:
      - "common/hello-world/*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '15.3.x'
    - run: npm install
    - run: cd common/hello-world
    - run: npm test